### ISSUE TITLE
Fatal error after installing the plugin

### ISSUE THREAD

**Issue by digi4care** [wpengine/wp-graphql-content-blocks#124]
I am getting an error after installing your plugin while i am going to the  GraphQL IDE. It keeps loading and never stop loading.

error: Uncaught Error: Class "WPGraphQLContentBlocksRegistryRegistry" not found in /var/www/html/wp-content/plugins/wp-graphql-content-blocks/includes/WPGraphQLContentBlocks.php:179

**Comment by theodesp** [comment]
Hey @digi4care. This seems strange there is a usage of the `Registry` class here:

https://github.com/wpengine/wp-graphql-content-blocks/blob/main/includes/WPGraphQLContentBlocks.php#L179

Did you use the releases tab to install the pluigin? Since it contains the relevant `vendor` and autoload packages:

https://github.com/wpengine/wp-graphql-content-blocks/releases

Also which PHP/WP versions are you using?

**Comment by mindctrl** [comment]
@digi4care going to close this. Feel free to reopen if you're still having issues.
