### ISSUE TITLE
Setup Content Block plugin updates through product info service

### ISSUE THREAD

**Issue by ChrisWiegman** [wpengine/wp-graphql-content-blocks#173]
**User Story**

As a WPGraphQL Content Blocks user, I want to have auto updates so that I don’t have to go back to GitHub each time.

We will serve product updates from WP Engine's wp-product-info service.

**Acceptance Criteria**
- [x] Plugin is added and configured in wp-product-info service
- [ ] Repo and main plugin file are renamed (see first comment below)
- [x] Plugin code retrieves update information from wp-product-info and passes it to WP
- [x] Releases are automated and pushed to wp-product-info
- [x] Updates for major breaking versions (semver) require the user confirm they want to install the update

**Technical Details**

wp-product-info is documented [here](https://docs.google.com/document/d/19ysfz2wNc1Hpp3M-u9w08JS2j4WUdSl7XRN_ZHWuIzg/edit#heading=h.c74m3a31hzsc)

The following plugins have good examples of integrating: [Interview API](https://github.com/wpengine/interview-api-wp), [Atlas Headless Extension](https://github.com/wpengine/wpe-atlas-headless-extension), [ACM](https://github.com/wpengine/atlas-content-modeler).

**Notes**

There might be a CircleCI requirement still in place for this but we don’t believe it should apply to our public repo. We can use CircleCI if it is required for this step.

**Comment by mindctrl** [comment]
Note: we are considering renaming the repo and main plugin file to align with wp.org standards, because at some point we may release this plugin there.

In this case, we would:
- rename the repo from `wp-graphql-content-blocks` to `wpgraphql-content-blocks` (removing the `-` after `wp`)
- rename the main plugin file from `wp-graphql-content-blocks.php` to `wpgraphql-content-blocks.php` (again removing the `-` after `wp`).

If anyone has thoughts or concerns about this change, please let us know.
