### ISSUE TITLE
Missing fields in GraphQL query

### ISSUE THREAD

**Issue by MKlblangenois** [wpengine/wp-graphql-content-blocks#225]
I recently upgrade WordPress core and plugins to the latest version, and now when I try to generate schemas, it gave me error about core blocks that missing some field (like `text` for `CoreButton` or `caption` for `CoreImage`)
![image](https://github.com/wpengine/wp-graphql-content-blocks/assets/42929225/03dbf291-f7ba-4f96-b1a7-8ede96bd873b)

When I inspect the schema.graphql from [the last release](https://github.com/wpengine/wp-graphql-content-blocks/releases/tag/v3.1.2), these fields exist but when I try to query them on GraphiQL IDE, they doesn't exist.
![SCR-20240403-irnt](https://github.com/wpengine/wp-graphql-content-blocks/assets/42929225/f4dc03b4-0dab-4757-822a-720c8237ea9d)

I've tried with default theme and other plugin disabled but the issue persist.

- Wordpress version: 6.5
- WPGraphQL: 1.22.1
- WPGraphQL Content Blocks: 3.1.2

**Comment by MKlblangenois** [comment]
After several tests, it seems that the problem comes from the update to WordPress 6.5, I tested up to 6.4.3 without problem

**Comment by theodesp** [comment]
@MKlblangenois it looks like WordPress does mess up their block fields with some breaking changes. At least GraphQL was able to detect any conflicts here before it's too late.

Hovever its quite tricky to rollout a new release of the blocks package since we will have to do a major upgrade release version to make this work. Clients could still be using old versions and if we update the fragments now it will break their code.

I could suggest to override the block fragments directly before you export them until we provide a new release.

Here is an example:
https://github.com/wpengine/faustjs/blob/canary/examples/next/block-support/wp-blocks/index.js
```
import { CoreBlocks } from '@faustwp/blocks';
import BlockB from './block-b/Component.js';
import { gql } from '@apollo/client';

CoreBlocks.CoreParagraph.fragments.entry = gql`

` // Update Fragment query here before exporting component.

export default {
  CoreParagraph: CoreBlocks.CoreParagraph,
  ...
````

**Comment by theodesp** [comment]
I could also suggest to open  ticket in https://github.com/wpengine/faustjs so that we are aware of this change.

**Comment by colis** [comment]
This is because the source for those blocks has changed to `rich-text`.

Adding `rich-text` as a case in the following switch should solve the problem

https://github.com/wpengine/wp-graphql-content-blocks/blob/9b0a63e24c1a1173c65b37de5523570aec65d332/includes/Blocks/Block.php#L370

**Comment by theodesp** [comment]
Hey @colis How on earth did they add this type without even documenting it? Strange. I will provide a PR today.

**Comment by theodesp** [comment]
Hey @colis latest version fixes this isse.
