### ISSUE TITLE
Add support for Reusable & Classic blocks

### ISSUE THREAD

**Issue by AndrewIontton93** [wpengine/wp-graphql-content-blocks#54]
Currently I cannot see a way to query reusable blocks or a classic block. I can see the typename available `CoreBlock` & `CoreFreeform`, however the blocks themselves don't actually appear in the page data. 

For example, the below query does not return 'core/block' or 'core/freeform' on a page which has those blocks added.

```
editorBlocks {
      name
}
```

**Comment by theodesp** [comment]
Hey @AndrewIontton93 thanks for the feedback.
Looking at the block.json for the `CoreFreeform` it looks like we need to handle an edge case here to retrieve the innerHTML for the block content.

Upon looking at the parsed `CoreFreeform` it looks like that Gutenberg does not save the `blockName` which is problematic:

```
{
  "data": {},
  "blockName": null,
  "attrs": [],
  "innerBlocks": [],
  "innerHTML": "\n\n<p>Example Freeform content</p>",
  "innerContent": [
    "\n\n<p>Example Freeform content</p>"
  ]
}
```

This is problematic since we are filtering the blocks that have no name even if they may have html content.

In that case I will open a ticket. to provide a custom handler for blocks that have no name to fallback to `CoreFreeform` as long as they are not empty.

As for the `reusable blocks` this would be a different ticket altogether.

I will let you know when we tackle the above issue with `CoreFreeform` since there is no

**Comment by theodesp** [comment]
@AndrewIontton93  we will be providing support for Classic blocks in this sprint.

**Comment by theodesp** [comment]
https://github.com/wpengine/wp-graphql-content-blocks/pull/59
