### ISSUE TITLE
WPGraphQL Content Blocks Plugin Error

### ISSUE THREAD

**Issue by RohitDokhe** [wpengine/wp-graphql-content-blocks#68]
Hello,

I have installed the “WPGraphQL Content Blocks” plugin and it activated successfully. However, I am getting an error when I try to open GraphQL IDE. It is showing a loader continues on screen and getting an error on screen “Parse error: syntax error, unexpected ‘WP_Block_Type’ (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/html/wp-content/plugins/wp-graphql-content-blocks/includes/Blocks/Block.php on line 30”.

Here are all the details about my website: 
PHP: Version 7.3.17 
WordPress Version 6.2 
Theme: WordPress Twenty Twenty-Three Version 1.1 
Plugin: WPGraphQL Version 1.14.3, 
		WPGraphQL Content Blocks Version 0.2.1

Could you please help me resolve this issue?

**Comment by justlevine** [comment]
> Here are all the details about my website:
> PHP: Version 7.3.17

@RohitDokhe The error you're seeing is due to the plugin's use of typed properties, which are only available in PHP 7.4. If you can update to that version (or even better PHP 8.0), that issue should go away.

PS @maintainers: running `composer phpcs` shows 17 PHP version compatibility issues and dozens of other failed sniffs.

![image](https://github.com/wpengine/wp-graphql-content-blocks/assets/29322304/483c9c6d-b543-4b71-8ec2-e12370570d63)

**Comment by mindctrl** [comment]
We should probably go ahead and bump the min PHP version. We currently have min at 7.2 ([source](https://github.com/wpengine/wp-graphql-content-blocks/blob/56f1b1ec70e0478a768c65c47bfa609720863405/wp-graphql-content-blocks.php#L12)).
